language: node_js
node_js:
  - "10"

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - npm ci

script:
  - npm run tslint
  - npm test -- --coverage

after_script:
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.json coverage/lcov.info
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi